// make this link to external source

// let externalLink = "https://docs.google.com/document/d/your-document-id/edit";
let questionsArray = [
  "What is your favouite kind of pen?",
  "Fave biscuit?",
  "Best hot drink?",
  "When did you first get drunk?",
  "Opinion of herbal tea?",
  "Fave media eg, tv, music, film, books, games?",
  "Fave pasta dish?",
  "Fave phone app?",
  "Fave veg by texture?",
  "Fave website?",
  "Favorite jacket in a film/tv show?",
  "Favorite pasta shape?",
  "Favourite canned fish?",
  "Favourite canned meat?",
  "Favourite Christmas film/music?",
  "Favourite cover song?",
  "Favourite kind of lamp?",
  "Favourite media?",
  "Favourite pjs as a kid?",
  "Favourite Sandwich (bread, filling, salad)?",
  "Favourite smell?",
  "whats posh stuff and whats poor stuff? eg Daddies brown sauce",
  "if you had a pet would you make them a social media account?",
  "What trait do you admire in other people?",
  "Ever been attacked by an animal?",
  "Can you dance, do you enjoy it?",
  "Do you like the spice girls?",
  "Do you know any girl/boy band dances?",
  "What preferences are you very specific about? eg headphones",
  "Current obsessions?",
  "drag or roller derby name?",
  "go to pot noodle flavour?",
  "Do you know any sign language?",
  "Do you have misophonia?",
  "fave task at work?",
  "fave household task? eg washing up",
  "have you ever used a scrub daddy?",
  "best way to cook eggs?",
  "music you like at the moment?",
  "have you ever fainted?",
  "how do you connect with people?",
  "why did you choose that outfit today?",
  "toilet phone calls?",
  "good things in a stir-fry?",
  "what behaviours do you find endearing?",
  "You see a spider in the bathroom, can you still commit to pooping?",
  "Sushi opinions?",
  "good candle smells?",
  "Can you handle sincere compliments?",
  "misconceptions about you?",
  "ever had a fishermans friend?",
  "ever been in a canoe",
  "what toy from childhood do you miss the most?",
  "weird/gross things youve found in bag or pockets?",
  "most appealing habit in friend/partner?",
  "what laws do you regularly break?",
  "is there any exercise you like?",
  "why would you never talk to your cousin again if you needed a reason?",
  "best advice received?",
  "song you find annoying?",
  "best burger?",
  "what card games do you know?",
  "do you like board games?",
  "longest holiday?",
  "best halloween costume?",
  "how many houses have you lived in?",
  "do you like olives?",
  "can you poop in public bathrooms?",
  "best kind of chips?",
  "eaten anything new?",
  "opinion of root beer?",
  "do you like sudoku?",
  "are you the person you thought youd be?",
  "when did you realize your sexuality/gender?",
  "do you enjoy food shopping, where do you go?",
  "opinion of littering?",
  "first ever date?",
  "when walking where do you look?",
  "ever flown a kite?",
  "fave train station?",
  "ever eaten anything in bath or shower?",
  "what do you wish you got taught in school?",
  "best toastie filling?",
  "have you ever planked?",
  "are you hard on yourself?",
  "have you ever written a poem?",
  "any song lyrics you like?",
  "when do you feel attractive?",
  "odd or matching socks?",
];

